#!/usr/bin/env bash

source bin/activate

# Freeze requirements
pip freeze > requirements.txt

# Generate wheelhouse
rm -rf wheelhouse
pip wheel --wheel-dir wheelhouse -r requirements.txt

# Remove unneeded cache files
find . -name '__pycache__' -type d -exec rm -r {} +
find . -name '*.pyc' -exec rm -f {} +
find . -name '*.pyo' -exec rm -f {} +
find . -name '*~' -exec rm -f {} +

# Zip files
zip -r test_bundle.zip tests/ wheelhouse/ requirements.txt
du -h test_bundle.zip
